In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()  # number of elements

12

In [5]:
x = x.reshape(3, 4) # reshape to 3 rows and 4 columns
print(x)
x = x.reshape(-1, 4) # -1 means infer the dimension from the remaining elements
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros(2, 3, 4) # 2 x 3 x 4 tensor of zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4)) # 2 x 3 x 4 tensor of ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(3, 4) # 3 x 4 tensor of random normal values

tensor([[ 1.7280, -0.0858,  0.8761,  1.2430],
        [-0.6683, -0.2229, -0.0095, -0.2568],
        [ 0.1016,  0.5242,  1.1035, -0.3991]])

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [10]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y # elementwise operations

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [11]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x,y), dim=0), torch.cat((x,y), dim=1) # concatenate along the first and second dimension

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [12]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
x.sum()

tensor(66.)

In [30]:
a = torch.arange(6).reshape((3,2))
b = torch.arange(3).reshape((1,3))
a, b

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 1, 2]]))

In [31]:
a + b # broadcasting must have at least one dimension of size 1

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [32]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [33]:
x[1, 2] = 9

In [34]:
before = id(y)
y = y + x
id(y) == before

False

In [36]:
z = torch.zeros_like(x)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 1891363731232
id(z): 1891363731232


In [39]:
before = id(x)
x += y
id(x) == before

False

In [53]:
x = torch.arange(6).reshape((2,3))
y = torch.arange(4).reshape((2,2))
x < y  # size of 1 tensor is broadcasted to size of 2 tensor

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1